### ISSUE TITLE
Graduate `rattler` to main `conda` organization

### ISSUE THREAD

**Issue by baszalmstra** [conda/rattler#799]
This project has been, and still is, actively maintained by among others @wolfv , @tdejager, and myself. It is used by [several](https://github.com/AaronOpfer/conda_curation) [projects](https://github.com/jaimergp/conda-rattler-solver) [in](https://github.com/synapticarbors/pixi2ces) [the](https://github.com/prefix-dev/rattler-build) [wild](https://github.com/Quantco/pixi-pack), inside a couple of large companies, in the https://prefix.dev backend, and of course in [pixi](https://github.com/prefix-dev/pixi).

Therefore **I would like to graduate `rattler` to the main `conda` organization.**

**Comment by baszalmstra** [comment]
Please use the following form to vote: 

@xhochy (Uwe Korn)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@cj-wright (Christopher J. 'CJ' Wright)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@mariusvniekerk (Marius van Niekerk)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@goanpeca (Gonzalo Peña-Castellanos)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@chenghlee (Cheng H. Lee)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@ocefpaf (Filipe Fernandes)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@marcelotrevisani (Marcelo Duarte Trevisani)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@msarahan (Michael Sarahan)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@mbargull (Marcel Bargull)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@jakirkham (John Kirkham)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@jezdez (Jannis Leidel)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@wolfv (Wolf Vollprecht)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@jaimergp (Jaime Rodríguez-Guerra)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@kkraus14 (Keith Kraus)
- [ ]  yes
- [ ]  no
- [ ]  abstain

@baszalmstra (Bas Zalmstra)
- [x]  yes
- [ ]  no
- [ ]  abstain

**Comment by baszalmstra** [comment]
@conda-incubator/steering-council This is a kind reminder to vote for this proposal, to graduate rattler to the main conda organization (also make sure your vote was actually recorded, apparently this can go wrong!). Thank you!

**Comment by baszalmstra** [comment]
@conda-incubator/steering-council The end of the vote is getting close! Not everyone has cast their vote yet. Please abstain if you do not plan to vote.

If you did vote, please make sure your vote was registered. Apparently, sometimes checking the checkmarks is not persisted.

**Comment by mbargull** [comment]
yes

**Comment by baszalmstra** [comment]
> yes

I took the liberty to tick the box for you. 👍

**Comment by baszalmstra** [comment]
This vote was closed, with the following result

Total voters: 15 (valid: 12 = 80.00%)

Yes votes (12 / 100.00%):
- @xhochy (Uwe Korn)
- @chenghlee (Cheng H. Lee)
- @ocefpaf (Filipe Fernandes)
- @marcelotrevisani (Marcelo Duarte Trevisani)
- @msarahan (Michael Sarahan)
- @mbargull (Marcel Bargull)
- @jakirkham (John Kirkham)
- @jezdez (Jannis Leidel)
- @wolfv (Wolf Vollprecht)
- @jaimergp (Jaime Rodríguez-Guerra)
- @kkraus14 (Keith Kraus)
- @baszalmstra (Bas Zalmstra)

No votes (0 / 0.00%)):

Abstain votes (0 / 0.00%):

Not voted (3):
- @cj-wright (Christopher J. 'CJ' Wright)
- @mariusvniekerk (Marius van Niekerk)
- @goanpeca (Gonzalo Peña-Castellanos)

Invalid votes (0):

We reached quorum, and enough YES votes to accept the proposal! 🎉

**Comment by jezdez** [comment]
Congratulations @conda/rattler!

I took the liberty to:

- [x] recrate the [rattler](https://github.com/orgs/conda/teams/rattler) team in the conda organization and invited the same people (please check your emails for the invite from GitHub!):

	- [x] @wolfv
	- [x] @baszalmstra
	- [ ] @ruben-arts
	- [ ] @nichmor
	- [ ] @Hofer-Julian 

- [x] transfer the repo, to https://github.com/conda/rattler
- [x] fix the team permissions to admin permissions for the repo

**Comment by tdejager** [comment]
> Congratulations @conda/rattler!
> 
> I took the liberty to:
> 
>     * [x]  recrate the [rattler](https://github.com/orgs/conda/teams/rattler) team in the conda organization and invite the same people (please check your emails for the invite from GitHub!):
>       
>       * [x]  @wolfv
>       * [x]  @baszalmstra
>       * [x]  @ruben-arts
>       * [x]  @nichmor
>       * [x]  @Hofer-Julian
> 
>     * [x]  transfer the repo, to [conda/rattler](https://github.com/conda/rattler)
> 
>     * [x]  fix the team permissions to admin permissions for the repo

Hi @jezdez can you also add me @tdejager :)?

**Comment by jezdez** [comment]
> Hi @jezdez can you also add me @tdejager :)?

Done, invite sent!
