### ISSUE TITLE
Many `__init__` are missing from documentation

### ISSUE THREAD

**Issue by calebzulawski** [conda/rattler#809]
I'm working on a `conda-lock`-ish custom tool for my company's build system.  The py-rattler API is great!  But I'm noticing many `__init__` functions are missing from the documentation, so I'm consulting the source.  Is this intentional and I shouldn't be using these constructors?  Maybe they can be added to the docs even without a docstring?

An example: creating a `LockFile` from `Environment`s, and creating `Environment` from `RepoDataRecord`s.

**Comment by wolfv** [comment]
That sounds great. If you have time to send a PR that would be heavily appreciated.

**Comment by wolfv** [comment]
As we merged the PR, let's close this issue! :)
