### ISSUE TITLE
Channel matching error when using authed URLs in package spec

### ISSUE THREAD

**Issue by jpcorreia99** [conda/rattler#830]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When installing a conda package, one can specify it under the shape `channel/platform::name-version-buildstring` to ensure the package is fetched from a specific channel.

To access the channel, users may provide a basic authentication url, such that the specification may look something like

`"https//:[password}@my.repository/conda/noarch::python-3.11-abcd"`. The user may then also pass the same URL as a conda channel to rattler `"https//:[password}@my.repository/conda"`. (We have to pass the whole URL otherwise rattler will think it is a suffix of `https://anaconda.org/`).

Even though these two are the same url and we'd expect rattler to pull the package from the provided repository, looking at the log lines we'll see 
`Ignoring python from https://:********@ my.repository/conda/ because it was not requested from that channel.`

This is because of this condition:https://github.com/conda/rattler/blob/8a397a08f2c79e2319f1e48724017c7988719a9b/crates/rattler_solve/src/resolvo/mod.rs#L321-L324

The variable on the left side has already been redacted, making the link contain the `"******"`string in place of a password. However, the right side has not, making the two mismatch. 

I was quickly able to fix it by changing `spec_channel.base_url.to_string()` to `spec_channel.canonical_name() `. I'd like to know what you think of the feasibility of this fix :) 

<br>
<br>
<br>

Btw, I noticed on the but template that it says `Thank you for helping to make conda/.github better. We would be unable to improve conda/.github without our community!`, you might want to change it!

**Comment by jpcorreia99** [comment]
Hey folks @baszalmstra @wolfv @nichmor it's another `dubious user usage` induced issue 😅 Would appreciate your opinions on it.

**Comment by jpcorreia99** [comment]
I'm also curious, is there a supported way of setting up aliases in rattler? (i.e. https://docs.conda.io/projects/conda/en/4.13.x/user-guide/configuration/use-condarc.html#set-ch-alias)

**Comment by jpcorreia99** [comment]
@baszalmstra little ping here :)

**Comment by baszalmstra** [comment]
Sorry Im a bit swamped, I hope to get to this very soon!

**Comment by jpcorreia99** [comment]
hey @baszalmstra little ping here in case you're more available now 😃

**Comment by jpcorreia99** [comment]
@baszalmstra @wolfv hey folks, sorry for another ping here 😅

**Comment by nichmor** [comment]
hey @jpcorreia99 ! sorry for such a long reply time.

I will take a look at this error later today - and will comeback with an answer! ( maybe even with a fix :D )

**Comment by jpcorreia99** [comment]
hey @nichmor thank you! I've already put up a fix actually! https://github.com/conda/rattler/pull/831

**Comment by nichmor** [comment]
oh, that's super nice! let me review it today !

**Comment by baszalmstra** [comment]
Thanks for the fix! Sorry for taking so long for this small change!
