### ISSUE TITLE
Add functionality to check whether a set of `PackageRecord`s is a valid solution or not

### ISSUE THREAD

**Issue by pavelzw** [conda/rattler#906]
### Checklist

- [x] I added a descriptive title
- [x] I searched open requests and couldn't find a duplicate

### What is the idea?

We would like to add a check in `pixi-pack pack --inject ...` (i.e. adding a package on top of a locked pixi env) that the injected packages form a valid environment.

### Additional Context

https://github.com/Quantco/pixi-pack/issues/48

**Comment by baszalmstra** [comment]
I think we could even implement this only for RepoDataRecord (a prefix record contains that)

**Comment by pavelzw** [comment]
We implemented this function in pixi-pack: https://github.com/Quantco/pixi-pack/blob/daf227ef11be67a109f5168b0d6d3c3fad3ca913/src/pack.rs#L409

@baszalmstra do you think it makes sense to upstream it here?

**Comment by baszalmstra** [comment]
Yeah for sure!
